[package]
name = "kafka-proxy"
version = "0.2.0"
authors = ["Eric Coan <ecoan@instructure.com>"]

[dependencies]

bodyparser = { git = "https://github.com/iron/body-parser.git" }
iron = "0.4.0"
kafka = "0.5.0"
lazy_static = "0.2.1"
openssl = "0.7.14"
router = "0.2.0"
